SAMPLE_MOVIES = [
    {
        "series_title": "The Shawshank Redemption",
        "released_year": 1994,
        "certificate": "R",
        "runtime": 142,
        "genre": "Drama",
        "imdb_rating": 9.3,
        "overview": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "meta_score": 80,
        "director": "Frank Darabont",
        "star1": "Tim Robbins",
        "star2": "Morgan Freeman",
        "star3": "Bob Gunton",
        "star4": "William Sadler",
        "no_of_votes": 2500000,
        "gross": "$28.34M"
    },
    {
        "series_title": "The Godfather",
        "released_year": 1972,
        "certificate": "R",
        "runtime": 175,
        "genre": "Crime, Drama",
        "imdb_rating": 9.2,
        "overview": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "meta_score": 90,
        "director": "Francis Ford Coppola",
        "star1": "Marlon Brando",
        "star2": "Al Pacino",
        "star3": "James Caan",
        "star4": "Diane Keaton",
        "no_of_votes": 1800000,
        "gross": "$134.97M"
    },
    {
        "series_title": "The Dark Knight",
        "released_year": 2008,
        "certificate": "PG-13",
        "runtime": 152,
        "genre": "Action, Crime, Drama",
        "imdb_rating": 9.0,
        "overview": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "meta_score": 84,
        "director": "Christopher Nolan",
        "star1": "Christian Bale",
        "star2": "Heath Ledger",
        "star3": "Aaron Eckhart",
        "star4": "Michael Caine",
        "no_of_votes": 2500000,
        "gross": "$534.86M"
    },
    {
        "series_title": "Pulp Fiction",
        "released_year": 1994,
        "certificate": "R",
        "runtime": 154,
        "genre": "Crime, Drama",
        "imdb_rating": 8.9,
        "overview": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "meta_score": 94,
        "director": "Quentin Tarantino",
        "star1": "John Travolta",
        "star2": "Uma Thurman",
        "star3": "Samuel L. Jackson",
        "star4": "Bruce Willis",
        "no_of_votes": 2000000,
        "gross": "$107.93M"
    },
    {
        "series_title": "Fight Club",
        "released_year": 1999,
        "certificate": "R",
        "runtime": 139,
        "genre": "Drama",
        "imdb_rating": 8.8,
        "overview": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        "meta_score": 66,
        "director": "David Fincher",
        "star1": "Brad Pitt",
        "star2": "Edward Norton",
        "star3": "Meat Loaf",
        "star4": "Zach Grenier",
        "no_of_votes": 2100000,
        "gross": "$37.03M"
    }
] 