SAMPLE_MOVIES = [
    {
        "series_title": "The Shawshank Redemption",
        "released_year": 1994,
        "certificate": "R",
        "runtime": 142,
        "genre": "Drama",
        "imdb_rating": 9.3,
        "overview": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "meta_score": 80,
        "director": "Frank Darabont",
        "star1": "Tim Robbins",
        "star2": "Morgan Freeman",
        "star3": "Bob Gunton",
        "star4": "William Sadler",
        "no_of_votes": 2500000,
        "gross": "$28.34M"
    },
    {
        "series_title": "The Godfather",
        "released_year": 1972,
        "certificate": "R",
        "runtime": 175,
        "genre": "Crime, Drama",
        "imdb_rating": 9.2,
        "overview": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "meta_score": 90,
        "director": "Francis Ford Coppola",
        "star1": "Marlon Brando",
        "star2": "Al Pacino",
        "star3": "James Caan",
        "star4": "Diane Keaton",
        "no_of_votes": 1800000,
        "gross": "$134.97M"
    },
    {
        "series_title": "The Dark Knight",
        "released_year": 2008,
        "certificate": "PG-13",
        "runtime": 152,
        "genre": "Action, Crime, Drama",
        "imdb_rating": 9.0,
        "overview": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "meta_score": 84,
        "director": "Christopher Nolan",
        "star1": "Christian Bale",
        "star2": "Heath Ledger",
        "star3": "Aaron Eckhart",
        "star4": "Michael Caine",
        "no_of_votes": 2500000,
        "gross": "$534.86M"
    },
    {
        "series_title": "Pulp Fiction",
        "released_year": 1994,
        "certificate": "R",
        "runtime": 154,
        "genre": "Crime, Drama",
        "imdb_rating": 8.9,
        "overview": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "meta_score": 94,
        "director": "Quentin Tarantino",
        "star1": "John Travolta",
        "star2": "Uma Thurman",
        "star3": "Samuel L. Jackson",
        "star4": "Bruce Willis",
        "no_of_votes": 2000000,
        "gross": "$107.93M"
    },
    {
        "series_title": "Fight Club",
        "released_year": 1999,
        "certificate": "R",
        "runtime": 139,
        "genre": "Drama",
        "imdb_rating": 8.8,
        "overview": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        "meta_score": 66,
        "director": "David Fincher",
        "star1": "Brad Pitt",
        "star2": "Edward Norton",
        "star3": "Meat Loaf",
        "star4": "Zach Grenier",
        "no_of_votes": 2100000,
        "gross": "$37.03M"
    },
    {
        "series_title": "Inception",
        "released_year": 2010,
        "certificate": "PG-13",
        "runtime": 148,
        "genre": "Action, Adventure, Sci-Fi",
        "imdb_rating": 8.8,
        "overview": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "meta_score": 74,
        "director": "Christopher Nolan",
        "star1": "Leonardo DiCaprio",
        "star2": "Joseph Gordon-Levitt",
        "star3": "Ellen Page",
        "star4": "Tom Hardy",
        "no_of_votes": 2300000,
        "gross": "$292.58M"
    },
    {
        "series_title": "The Matrix",
        "released_year": 1999,
        "certificate": "R",
        "runtime": 136,
        "genre": "Action, Sci-Fi",
        "imdb_rating": 8.7,
        "overview": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        "meta_score": 73,
        "director": "Lana Wachowski",
        "star1": "Keanu Reeves",
        "star2": "Laurence Fishburne",
        "star3": "Carrie-Anne Moss",
        "star4": "Hugo Weaving",
        "no_of_votes": 1900000,
        "gross": "$171.48M"
    },
    {
        "series_title": "Forrest Gump",
        "released_year": 1994,
        "certificate": "PG-13",
        "runtime": 142,
        "genre": "Drama, Romance",
        "imdb_rating": 8.8,
        "overview": "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
        "meta_score": 82,
        "director": "Robert Zemeckis",
        "star1": "Tom Hanks",
        "star2": "Robin Wright",
        "star3": "Gary Sinise",
        "star4": "Sally Field",
        "no_of_votes": 2000000,
        "gross": "$330.25M"
    },
    {
        "series_title": "The Silence of the Lambs",
        "released_year": 1991,
        "certificate": "R",
        "runtime": 118,
        "genre": "Crime, Drama, Thriller",
        "imdb_rating": 8.6,
        "overview": "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
        "meta_score": 85,
        "director": "Jonathan Demme",
        "star1": "Jodie Foster",
        "star2": "Anthony Hopkins",
        "star3": "Lawrence A. Bonney",
        "star4": "Kasi Lemmons",
        "no_of_votes": 1400000,
        "gross": "$130.74M"
    },
    {
        "series_title": "The Lord of the Rings: The Fellowship of the Ring",
        "released_year": 2001,
        "certificate": "PG-13",
        "runtime": 178,
        "genre": "Adventure, Fantasy",
        "imdb_rating": 8.8,
        "overview": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        "meta_score": 92,
        "director": "Peter Jackson",
        "star1": "Elijah Wood",
        "star2": "Ian McKellen",
        "star3": "Orlando Bloom",
        "star4": "Sean Bean",
        "no_of_votes": 1800000,
        "gross": "$315.54M"
    },
    {
        "series_title": "Interstellar",
        "released_year": 2014,
        "certificate": "PG-13",
        "runtime": 169,
        "genre": "Adventure, Drama, Sci-Fi",
        "imdb_rating": 8.6,
        "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "meta_score": 74,
        "director": "Christopher Nolan",
        "star1": "Matthew McConaughey",
        "star2": "Anne Hathaway",
        "star3": "Jessica Chastain",
        "star4": "Michael Caine",
        "no_of_votes": 1700000,
        "gross": "$188.02M"
    },
    {
        "series_title": "The Green Mile",
        "released_year": 1999,
        "certificate": "R",
        "runtime": 189,
        "genre": "Crime, Drama, Fantasy",
        "imdb_rating": 8.6,
        "overview": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        "meta_score": 61,
        "director": "Frank Darabont",
        "star1": "Tom Hanks",
        "star2": "Michael Clarke Duncan",
        "star3": "David Morse",
        "star4": "Bonnie Hunt",
        "no_of_votes": 1300000,
        "gross": "$136.80M"
    },
    {
        "series_title": "The Prestige",
        "released_year": 2006,
        "certificate": "PG-13",
        "runtime": 130,
        "genre": "Drama, Mystery, Thriller",
        "imdb_rating": 8.5,
        "overview": "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
        "meta_score": 66,
        "director": "Christopher Nolan",
        "star1": "Christian Bale",
        "star2": "Hugh Jackman",
        "star3": "Scarlett Johansson",
        "star4": "Michael Caine",
        "no_of_votes": 1300000,
        "gross": "$53.09M"
    },
    {
        "series_title": "Gladiator",
        "released_year": 2000,
        "certificate": "R",
        "runtime": 155,
        "genre": "Action, Adventure, Drama",
        "imdb_rating": 8.5,
        "overview": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        "meta_score": 67,
        "director": "Ridley Scott",
        "star1": "Russell Crowe",
        "star2": "Joaquin Phoenix",
        "star3": "Connie Nielsen",
        "star4": "Oliver Reed",
        "no_of_votes": 1500000,
        "gross": "$187.71M"
    },
    {
        "series_title": "The Departed",
        "released_year": 2006,
        "certificate": "R",
        "runtime": 151,
        "genre": "Crime, Drama, Thriller",
        "imdb_rating": 8.5,
        "overview": "An undercover cop and a mole in the police force attempt to identify each other while infiltrating an Irish gang in South Boston.",
        "meta_score": 85,
        "director": "Martin Scorsese",
        "star1": "Leonardo DiCaprio",
        "star2": "Matt Damon",
        "star3": "Jack Nicholson",
        "star4": "Mark Wahlberg",
        "no_of_votes": 1300000,
        "gross": "$132.38M"
    },
    {
        "series_title": "The Social Network",
        "released_year": 2010,
        "certificate": "PG-13",
        "runtime": 120,
        "genre": "Biography, Drama",
        "imdb_rating": 7.7,
        "overview": "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.",
        "meta_score": 95,
        "director": "David Fincher",
        "star1": "Jesse Eisenberg",
        "star2": "Andrew Garfield",
        "star3": "Justin Timberlake",
        "star4": "Rooney Mara",
        "no_of_votes": 700000,
        "gross": "$96.96M"
    },
    {
        "series_title": "Whiplash",
        "released_year": 2014,
        "certificate": "R",
        "runtime": 106,
        "genre": "Drama, Music",
        "imdb_rating": 8.5,
        "overview": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
        "meta_score": 88,
        "director": "Damien Chazelle",
        "star1": "Miles Teller",
        "star2": "J.K. Simmons",
        "star3": "Melissa Benoist",
        "star4": "Paul Reiser",
        "no_of_votes": 800000,
        "gross": "$13.09M"
    },
    {
        "series_title": "The Grand Budapest Hotel",
        "released_year": 2014,
        "certificate": "R",
        "runtime": 99,
        "genre": "Adventure, Comedy, Crime",
        "imdb_rating": 8.1,
        "overview": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
        "meta_score": 88,
        "director": "Wes Anderson",
        "star1": "Ralph Fiennes",
        "star2": "F. Murray Abraham",
        "star3": "Mathieu Amalric",
        "star4": "Adrien Brody",
        "no_of_votes": 800000,
        "gross": "$59.10M"
    },
    {
        "series_title": "Parasite",
        "released_year": 2019,
        "certificate": "R",
        "runtime": 132,
        "genre": "Drama, Thriller",
        "imdb_rating": 8.5,
        "overview": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        "meta_score": 96,
        "director": "Bong Joon Ho",
        "star1": "Song Kang-ho",
        "star2": "Lee Sun-kyun",
        "star3": "Cho Yeo-jeong",
        "star4": "Choi Woo-shik",
        "no_of_votes": 700000,
        "gross": "$53.37M"
    },
    {
        "series_title": "Everything Everywhere All at Once",
        "released_year": 2022,
        "certificate": "R",
        "runtime": 139,
        "genre": "Action, Adventure, Comedy",
        "imdb_rating": 8.0,
        "overview": "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
        "meta_score": 81,
        "director": "Daniel Kwan",
        "star1": "Michelle Yeoh",
        "star2": "Stephanie Hsu",
        "star3": "Ke Huy Quan",
        "star4": "Jamie Lee Curtis",
        "no_of_votes": 500000,
        "gross": "$70.00M"
    }
] 